# Generated by Django 2.2.4 on 2019-08-21 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpostreply',
            name='forum_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ForumPost'),
        ),
        migrations.AlterField(
            model_name='forumpostreply',
            name='post',
            field=models.TextField(blank=True, null=True),
        ),
    ]
