# Generated by Django 2.2.4 on 2019-08-21 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190821_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumpost',
            old_name='user',
            new_name='sender',
        ),
    ]
