# Generated by Django 2.2.4 on 2019-08-26 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190821_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='post',
            field=models.TextField(default='This post is kept empty as it was created during production for test purpose only'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='title',
            field=models.TextField(default='This title is kept empty as it was created during production for test purpose only'),
        ),
        migrations.AlterField(
            model_name='forumpostreply',
            name='forum_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ForumPost'),
        ),
        migrations.AlterField(
            model_name='forumpostreply',
            name='post',
            field=models.TextField(default='This post is kept empty as it was created during production for test purpose only'),
        ),
    ]
