# Generated by Django 2.2.4 on 2019-08-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190826_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='post',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='forumpostreply',
            name='post',
            field=models.TextField(),
        ),
    ]
