# Generated by Django 2.2.4 on 2019-08-19 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tut_id', models.PositiveSmallIntegerField(auto_created=True, verbose_name='tutorial number')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('lesson', models.TextField(verbose_name='Complete lesson : use html tags in here')),
            ],
        ),
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tut_id', models.PositiveSmallIntegerField(auto_created=True, verbose_name='tutorial number')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='content/media/video_tutorials/')),
                ('video_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='series',
            name='number_of_videos',
        ),
        migrations.AddField(
            model_name='series',
            name='number_of_tuts',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='template',
            field=models.ImageField(blank=True, null=True, upload_to='content/media/images/template_images/'),
        ),
        migrations.AddField(
            model_name='series',
            name='template_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('TEXT', 'Text')], default='TEXT', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.AddField(
            model_name='videotutorial',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Series'),
        ),
        migrations.AddField(
            model_name='texttutorial',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Series'),
        ),
        migrations.AlterUniqueTogether(
            name='videotutorial',
            unique_together={('series', 'tut_id')},
        ),
        migrations.AlterUniqueTogether(
            name='texttutorial',
            unique_together={('series', 'tut_id')},
        ),
    ]
