# Generated by Django 2.2.4 on 2019-08-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20190819_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='subscribed_users',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
