# Generated by Django 2.2.4 on 2019-08-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20190820_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('TEXT', 'Text'), ('BOTH', 'Video and Text Combined')], max_length=100),
        ),
    ]
